apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created 
  #in the Kubernetes cluster
  name: service 
spec:
  selector:
    app: python-app 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 5000 #Service port
    targetPort: 5000 #The port for the React.js application container
